function [J, policy, lambda, Info] = ...
    computeOptimalPolicy(self, previousSolution, state, discreteState, t, writeLog)

state = self.cropToEligibleState(state);
if (nargin < 6)
    [J, policy, lambda, Info] = ...
        self.computeOptimalPolicy@LifecycleProblem(...
        previousSolution, state, discreteState, t);
else
    [J, policy, lambda, Info] = ...
        self.computeOptimalPolicy@LifecycleProblem(...
        previousSolution, state, discreteState, t, writeLog);
end